
GET http://localhost:3000/dashboard HTTP/1.1

###
POST http://localhost:3000/dashboard/ HTTP/1.1
content-type: application/json

{"user":{"name":"Dogukan"}, task:"bla bla"}

###
GET http://localhost:3000/dashboard/aa13 HTTP/1.1

###
DELETE  http://localhost:3000/dashboard/aa13 HTTP/1.1
